### ISSUE TITLE
pNSGAIIRegion algorithm does not work with the epsilon-dominance comparator

### ISSUE THREAD

**Issue by mceska** [gerasimou/SBMS#5]
The algorithm throws the following execution:
java.lang.ArrayIndexOutOfBoundsException: 2
    at evochecker.genetic.jmetal.util.RegionRanking.getSubfront(RegionRanking.java:157)
    at evochecker.genetic.jmetal.metaheuristics.pNSGAIIRegion.execute(pNSGAIIRegion.java:190)
    at evochecker.EvoChecker.execute(EvoChecker.java:167)
    at evochecker.EvoChecker.main(EvoChecker.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

The problem is in the region ranking algorithm -- it doesn't work with the epsilon comparator. Note that this problem occurs also if only a single core computation is executed.

**Comment by gerasimou** [comment]
Error trace from Nicola

This is the error trace:

```
java.lang.ArrayIndexOutOfBoundsException: 2
    at evochecker.genetic.jmetal.util.RegionRanking.getSubfront(RegionRanking.java:173)
    at evochecker.genetic.jmetal.metaheuristics.pNSGAIIRegion.execute(pNSGAIIRegion.java:190)
    at evochecker.EvoChecker.execute(EvoChecker.java:168)
    at evochecker.EvoChecker.main(EvoChecker.java:77)
```

I analysed a bit more in depth the issue. I’ve used the \epsilon-tolerance comparator.
The problem is that, when selecting the new population in pNSGAIIRegion.java, at times, the computed fronts do not contain all the expected solutions (that are, OLD POPULATION + OFFSPRINGS).

I printed on screen some numbers before this error was thrown

---

|POPULATION + OFFSPRING| = 100
sum_i |front[i]| = 4
sum_i |ranking[i]| = 4

---

This is from doRanking() in RegionRanking.java.
the 2nd and 3rd lines refer to the number of solutions in the front[] variable and in the ranking[] variable (they are the same, but ‘ranking’ has the correct length)
Clearly, all should be = 100. This indeed happens always, but when the error is thrown.

Maybe we have some problems in lines 117-133 of doRanking(), where the fronts are computed based on dominateMe and iDominate variables.
It seems like that one front is skipped, e.g. the loop exits because the next front is empty, while there are other solutions to be allocated yet. 
This is also inconsistent with the functioning of the sorting algorithm, this situation shouldn’t happen.

See indeed below the values of variable dominateMe before throwing the error

```
dominateMe[0] = 0
dominateMe[1] = 0
dominateMe[2] = 0
dominateMe[3] = 1
dominateMe[4] = 2
dominateMe[5] = 2
dominateMe[6] = 3
dominateMe[7] = 3
dominateMe[8] = 4
dominateMe[9] = 0
dominateMe[10] = 5
dominateMe[11] = 6
```

**Comment by mceska** [comment]
Note that Nicola meant the epsilon-dominance comparator, so it is the same issue.

**Comment by mceska** [comment]
This is the solution: basically if the value of the objective is negative then use (1-epsilon)v1 < v2. Note that the sensitivity should be correct i.e. the volume is always a positive number. But Simos pls check
that  getObjectiveBounds(i)[1] is ready the worst case for maximising objectives.

public int compare(Object object1, Object object2) {
        if (object1==null)
            return 1;
        else if (object2 == null)
            return -1;

```
    evochecker.genetic.jmetal.encoding.solution.RegionSolution solution1 = (evochecker.genetic.jmetal.encoding.solution.RegionSolution)object1;
    evochecker.genetic.jmetal.encoding.solution.RegionSolution solution2 = (evochecker.genetic.jmetal.encoding.solution.RegionSolution)object2;

    int dominate1 ; // dominate1 indicates if some objective of solution1
    // dominates the same objective in solution2. dominate2
    int dominate2 ; // is the complementary of dominate1.

    dominate1 = 0 ;
    dominate2 = 0 ;

    int flag; //stores the result of the comparison

    // Test to determine whether at least a solution violates some constraint
    // No constraints YET

    // Equal number of violated constraints. Applying a dominance Test then
    double value1, value2, vol1 = 0, vol2 = 0;
    for (int i = 0; i < solution1.getNumberOfObjectives(); i++) {
        value1 = solution1.getObjectiveBounds(i)[1]; // maxBound = worst case
        value2 = solution2.getObjectiveBounds(i)[1]; // maxBound = worst case
        if (i == 0){
            vol1 = value1 - solution1.getObjectiveBounds(i)[0];
            vol2 = value2 - solution2.getObjectiveBounds(i)[0];
        } else {
            vol1 = vol1 * (value1 - solution1.getObjectiveBounds(i)[0]);
            vol2 = vol2 * (value2 - solution2.getObjectiveBounds(i)[0]);
        }
        if (value1 >= 0.0){
            if ((1+epsilon)*value1 < value2) {
                flag = -1;
            } else if (value1 > (1+epsilon)*value2) {
                flag = 1;
            } else {
                flag = 0;
            }
        }
        else {
            if ((1-epsilon)*value1 < value2) {
                flag = -1;
            } else if (value1 > (1-epsilon)*value2) {
                flag = 1;
            } else {
                flag = 0;
            }
        }

        if (flag == -1) {
            dominate1 = 1;
        }

        if (flag == 1) {
            dominate2 = 1;
        }
    }

    // sensitivity - I don't use the volume of the parameter space since it is fixed
    if (sensitivity) {
        if ((1+epsilon)*vol1 < vol2) {
            flag = -1;
        } else if (vol1 > (1+epsilon)*vol2) {
            flag = 1;
        } else {
            flag = 0;
        }

        if (flag == -1) {
            dominate1 = 1;
        }

        if (flag == 1) {
            dominate2 = 1;
        }
    }

    if (dominate1 == dominate2) {
        return 0; //No one dominate the other
    }
    if (dominate1 == 1) {
        return -1; // solution1 dominate
    }
    return 1;    // solution2 dominate
} // compare
```
